### ISSUE TITLE
Error on installing in Delphi 10.4

### ISSUE THREAD

**Issue by RaulWW** [Code4Delphi/Code4D-Wizard#1]
![1](https://github.com/Code4Delphi/Code4D-Wizard/assets/75748993/bc9992f3-64af-4dde-a6b2-eaf1861c8b17)

**Comment by RaulWW** [comment]
![image](https://github.com/Code4Delphi/Code4D-Wizard/assets/75748993/0d347b21-4e87-49d4-a35a-3520761375c0)

**Comment by Cesar4D** [comment]
Hi Raul, we will analyze it and get back to you soon. We appreciate his message.

**Comment by Cesar4D** [comment]
Hello Raul Walter, we did the test by downloading the .bpl file (Install-BPLs/Delphi-10.4-Sydney/C4DWizard.bpl) and we were able to install normally in Delphi 10.4 Sydney.
I ask that you try to run it again, and if it doesn't work, try installing directly from the project. Just clone the repository on your computer, open the file 'Package\C4DWizard.dproj' in your Delphi, compile it and then install it in your IDE.
I ask that you try this, and let us know if it worked or not, so that we can help you.
We appreciate your contact, and we remain at your disposal.
